package com.csc.fsg.bpo.uniatriage.uniatriage_webapp;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Triage extends VerticalLayout {
	protected Grid<com.csc.fsg.bpo.uniatriage.uniatriage_webapp.model.Policy> policyGrid;
	protected Grid<com.csc.fsg.bpo.uniatriage.uniatriage_webapp.model.Agent> agentGrid;

	public Triage() {
		Design.read(this);
	}
}
